export const SELECT_LANGUAGE = 'SELECT_LANGUAGE'

export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN'

export const GET_USER_DETAILS_LOADING = 'GET_USER_DETAILS_LOADING'
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'

export const BROWSE_CATEGORIES_LOADING = 'BROWSE_CATEGORIES_LOADING'
export const BROWSE_CATEGORIES_SUCCESS = 'BROWSE_CATEGORIES_SUCCESS'
export const BROWSE_CATEGORIES_ERROR = 'BROWSE_CATEGORIES_ERROR'

export const BROWSE_FEATURED_PLAYLISTS_LOADING =
  'BROWSE_FEATURED_PLAYLISTS_LOADING'
export const BROWSE_FEATURED_PLAYLISTS_SUCCESS =
  'BROWSE_FEATURED_PLAYLISTS_SUCCESS'
export const BROWSE_FEATURED_PLAYLISTS_ERROR = 'BROWSE_FEATURED_PLAYLISTS_ERROR'

export const GET_PLAYLIST_LOADING = 'GET_PLAYLIST_LOADING'
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS'
export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR'

export const GET_NEW_RELEASES_LOADING = 'GET_NEW_RELEASES_LOADING'
export const GET_NEW_RELEASES_SUCCESS = 'GET_NEW_RELEASES_SUCCESS'
export const GET_NEW_RELEASES_ERROR = 'GET_NEW_RELEASES_ERROR'

export const GET_TOP_ARTISTS_LOADING = 'GET_TOP_ARTISTS_LOADING'
export const GET_TOP_ARTISTS_SUCCESS = 'GET_TOP_ARTISTS_SUCCESS'
export const GET_TOP_ARTISTS_ERROR = 'GET_TOP_ARTISTS_ERROR'

export const GET_SEARCH_RESULTS_LOADING = 'GET_SEARCH_RESULTS_LOADING'
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS'
export const GET_SEARCH_RESULTS_ERROR = 'GET_SEARCH_RESULTS_ERROR'

export const DISPLAY_DEFAULT_SEARCH_CATEGORIES =
  'DISPLAY_DEFAULT_SEARCH_CATEGORIES'
