export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN'

export const GET_USER_DETAILS_LOADING = 'GET_USER_DETAILS_LOADING'
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
