export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SELECT_LANGUAGE = 'SELECT_LANGUAGE'

export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN'

export const GET_USER_DETAILS_LOADING = 'GET_USER_DETAILS_LOADING'
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'

export const BROWSE_CATEGORIES_LOADING = 'BROWSE_CATEGORIES_LOADING'
export const BROWSE_CATEGORIES_SUCCESS = 'BROWSE_CATEGORIES_SUCCESS'
export const BROWSE_CATEGORIES_ERROR = 'BROWSE_CATEGORIES_ERROR'

export const BROWSE_FEATURED_PLAYLISTS_LOADING =
  'BROWSE_FEATURED_PLAYLISTS_LOADING'
export const BROWSE_FEATURED_PLAYLISTS_SUCCESS =
  'BROWSE_FEATURED_PLAYLISTS_SUCCESS'
export const BROWSE_FEATURED_PLAYLISTS_ERROR = 'BROWSE_FEATURED_PLAYLISTS_ERROR'
